export const DISPATCH_ASSET = "DISPATCH_ASSET";
export const RECEIVE_ASSET = "RECEIVE_ASSET";
export const EDIT_ASSET_NAME = "EDIT_ASSET_NAME";
export const EDIT_ASSET_COMMENT = "EDIT_ASSET_COMMENT";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const LOGGED_OUT = "LOGGED_OUT";
